//! Compile the vendored IFAP/FACR lookup tables (CSV, hash-verified against the
//! specs) into sorted `static` slices under `OUT_DIR`, included by `src/tables.rs`.
//!
//! Every table is pinned to Unicode 7.0.0 — that is the whole point of bundling
//! them rather than reaching for a general Unicode crate that tracks a newer
//! version. We never parse at runtime: lookups are binary searches over the
//! emitted slices.
//!
//! Two table shapes cover all 34 files:
//!   * range/set tables  — col 0 is a code point or `aaaa..bbbb` range, with an
//!     optional scalar second column (combining class, joining type, bidi class,
//!     eligibility flag, decimal-range id).
//!   * mapping tables    — col 0 is a single code point, col 1 a space-separated
//!     (possibly empty) array of code points (decompositions, case folds,
//!     convergence skeletons). ILT02 carries a third column we use to build the
//!     canonical-composition reverse table.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::{env, fs};

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let ifap = manifest.join("tables/ifap");
    let facr = manifest.join("tables/facr");
    println!("cargo:rerun-if-changed=tables");
    println!("cargo:rerun-if-changed=build.rs");

    let mut out = String::new();
    out.push_str("// @generated by build.rs from the vendored IFAP/FACR lookup tables.\n\n");

    // ---- IFAP (ILT) ----------------------------------------------------------
    emit_range_set(&mut out, "ILT01_CHARACTER_SET", &read(&ifap, "ilt01-character-set"));
    emit_canonical(&mut out, &read(&ifap, "ilt02-canonical-mapping"));
    emit_mapping(&mut out, "ILT03_COMPAT", &read(&ifap, "ilt03-compatibility-mapping"));
    emit_range_scalar(&mut out, "ILT04_CCC", &read(&ifap, "ilt04-combining-class"), ScalarKind::Int);
    emit_range_set(&mut out, "ILT06_COMBINING_MARKS", &read(&ifap, "ilt06-combining-marks"));
    emit_range_scalar(&mut out, "ILT07_JOINING", &read(&ifap, "ilt07-joining-type"), ScalarKind::Byte);
    emit_eligible(&mut out, &read(&ifap, "ilt08-eligible-characters"));
    emit_range_scalar(&mut out, "ILT09_BIDI", &read(&ifap, "ilt09-bidi-class"), ScalarKind::Bidi);
    emit_range_set(&mut out, "ILT10_DECIMAL", &read(&ifap, "ilt10-decimal-numbers"));
    emit_mapping(&mut out, "ILT11_FOLD", &read(&ifap, "ilt11-nfkc-case-folding"));

    // ---- FACR (FLT) ----------------------------------------------------------
    let employable = [
        ("FLT01_LATIN", "flt01-lc-latin-employable"),
        ("FLT02_CHINESE", "flt02-lc-chinese-employable"),
        ("FLT03_JAPANESE", "flt03-lc-japanese-employable"),
        ("FLT04_KOREAN", "flt04-lc-korean-employable"),
        ("FLT05_ARABIC", "flt05-lc-arabic-employable"),
        ("FLT06_CYRILLIC", "flt06-lc-cyrillic-employable"),
        ("FLT07_HEBREW", "flt07-lc-hebrew-employable"),
        ("FLT08_DEVANAGARI", "flt08-lc-devanagari-employable"),
        ("FLT09_THAI", "flt09-lc-thai-employable"),
        ("FLT10_GREEK", "flt10-lc-greek-employable"),
    ];
    for (name, file) in employable {
        emit_range_set(&mut out, &format!("{name}_EMPLOYABLE"), &read(&facr, file));
    }

    // Native-character sets for the arrangement "native" rule (§4.2): the
    // employable code points whose `SCRIPT` column names a script that belongs
    // to the category's own writing system.
    let native: [(&str, &str, &[&str]); 4] = [
        ("FLT02_CHINESE_NATIVE", "flt02-lc-chinese-employable", &["Han"]),
        (
            "FLT03_JAPANESE_NATIVE",
            "flt03-lc-japanese-employable",
            &["Han", "Hiragana", "Katakana"],
        ),
        ("FLT04_KOREAN_NATIVE", "flt04-lc-korean-employable", &["Hangul", "Han"]),
        ("FLT09_THAI_NATIVE", "flt09-lc-thai-employable", &["Thai"]),
    ];
    for (name, file, scripts) in native {
        emit_native(&mut out, name, &read(&facr, file), scripts);
    }

    emit_range_scalar(
        &mut out,
        "FLT11_DECIMAL_RANGE",
        &read(&facr, "flt11-decimal-number-ranges"),
        ScalarKind::Int,
    );

    let convergence = [
        ("FLT12_LATIN_CONFUSABLE", "flt12-intra-lc-latin-confusable"),
        ("FLT13_CHINESE_CONFUSABLE", "flt13-intra-lc-chinese-confusable"),
        ("FLT14_CHINESE_VARIANT", "flt14-intra-lc-chinese-variant"),
        ("FLT15_JAPANESE_CONFUSABLE", "flt15-intra-lc-japanese-confusable"),
        ("FLT16_KOREAN_CONFUSABLE", "flt16-intra-lc-korean-confusable"),
        ("FLT17_ARABIC_CONFUSABLE", "flt17-intra-lc-arabic-confusable"),
        ("FLT18_CYRILLIC_CONFUSABLE", "flt18-intra-lc-cyrillic-confusable"),
        ("FLT19_HEBREW_CONFUSABLE", "flt19-intra-lc-hebrew-confusable"),
        ("FLT20_DEVANAGARI_CONFUSABLE", "flt20-intra-lc-devanagari-confusable"),
        ("FLT21_THAI_CONFUSABLE", "flt21-intra-lc-thai-confusable"),
        ("FLT22_GREEK_CONFUSABLE", "flt22-intra-lc-greek-confusable"),
        ("FLT23_INTER_LC", "flt23-inter-lc"),
    ];
    for (name, file) in convergence {
        emit_mapping(&mut out, name, &read(&facr, file));
    }

    let dest = PathBuf::from(env::var("OUT_DIR").unwrap()).join("tables.rs");
    fs::write(dest, out).unwrap();
}

/// Read a vendored table by its label stem (the `ilt07-joining-type` part of the
/// full `ifap11-adopted.spec.ilt07-joining-type.txt` / `facr10-adopted.spec.…`
/// file name). Panics loudly if the expected file is missing — a build-time
/// guarantee that the data set is complete.
fn read(dir: &Path, stem: &str) -> String {
    for entry in fs::read_dir(dir).unwrap() {
        let path = entry.unwrap().path();
        let name = path.file_name().unwrap().to_string_lossy();
        if name.contains(stem) {
            return fs::read_to_string(&path).unwrap();
        }
    }
    panic!("missing lookup table for `{stem}` in {}", dir.display());
}

/// The data lines of a table: skip `#` comments and the single header line.
fn data_lines(text: &str) -> impl Iterator<Item = &str> {
    text.lines()
        .filter(|l| !l.is_empty() && !l.starts_with('#'))
        .skip(1)
}

fn parse_cp(s: &str) -> u32 {
    u32::from_str_radix(s.trim(), 16).unwrap_or_else(|_| panic!("bad code point {s:?}"))
}

/// `aaaa` -> `(a, a)`, `aaaa..bbbb` -> `(a, b)` (both ends inclusive).
fn parse_col0(s: &str) -> (u32, u32) {
    match s.split_once("..") {
        Some((a, b)) => (parse_cp(a), parse_cp(b)),
        None => {
            let c = parse_cp(s);
            (c, c)
        }
    }
}

fn parse_cp_list(s: &str) -> Vec<u32> {
    let s = s.trim();
    if s.is_empty() {
        return Vec::new();
    }
    s.split_whitespace().map(parse_cp).collect()
}

enum ScalarKind {
    Int,
    Byte,
    Bidi,
}

fn emit_range_set(out: &mut String, name: &str, text: &str) {
    let mut ranges: Vec<(u32, u32)> = data_lines(text)
        .map(|l| parse_col0(l.split(',').next().unwrap()))
        .collect();
    ranges.sort_unstable();
    write!(out, "pub static {name}: &[(u32, u32)] = &[").unwrap();
    for (a, b) in ranges {
        write!(out, "({a},{b}),").unwrap();
    }
    out.push_str("];\n");
}

/// ILT08: only the rows whose `IS_ELIGIBLE` flag is `1` form the eligible set;
/// everything else (explicit `0` rows and absent code points alike) is rejected.
fn emit_eligible(out: &mut String, text: &str) {
    let mut ranges = Vec::new();
    for l in data_lines(text) {
        let mut it = l.split(',');
        let r = parse_col0(it.next().unwrap());
        if it.next().unwrap().trim() == "1" {
            ranges.push(r);
        }
    }
    ranges.sort_unstable();
    write!(out, "pub static ILT08_ELIGIBLE: &[(u32, u32)] = &[").unwrap();
    for (a, b) in ranges {
        write!(out, "({a},{b}),").unwrap();
    }
    out.push_str("];\n");
}

/// Emit the subset of an employable table whose `SCRIPT` column is one of
/// `scripts` (a native writing system of the category) as a range set.
fn emit_native(out: &mut String, name: &str, text: &str, scripts: &[&str]) {
    let mut ranges = Vec::new();
    for l in data_lines(text) {
        let mut it = l.split(',');
        let r = parse_col0(it.next().unwrap());
        let script = it.next().unwrap_or("").trim();
        if scripts.contains(&script) {
            ranges.push(r);
        }
    }
    ranges.sort_unstable();
    write!(out, "pub static {name}: &[(u32, u32)] = &[").unwrap();
    for (a, b) in ranges {
        write!(out, "({a},{b}),").unwrap();
    }
    out.push_str("];\n");
}

fn emit_range_scalar(out: &mut String, name: &str, text: &str, kind: ScalarKind) {
    let mut rows: Vec<(u32, u32, u32)> = data_lines(text)
        .map(|l| {
            let mut it = l.split(',');
            let (a, b) = parse_col0(it.next().unwrap());
            let v = it.next().unwrap().trim();
            let scalar = match kind {
                ScalarKind::Int => v.parse::<u32>().unwrap(),
                ScalarKind::Byte => v.bytes().next().unwrap() as u32,
                ScalarKind::Bidi => bidi_code(v) as u32,
            };
            (a, b, scalar)
        })
        .collect();
    rows.sort_unstable();
    write!(out, "pub static {name}: &[(u32, u32, u32)] = &[").unwrap();
    for (a, b, v) in rows {
        write!(out, "({a},{b},{v}),").unwrap();
    }
    out.push_str("];\n");
}

/// Bidi class -> stable numeric code shared with `src/tables.rs`. `L` is the
/// NULL default and never appears in ILT09, so it has no code here.
fn bidi_code(s: &str) -> u8 {
    match s {
        "R" => 1,
        "AL" => 2,
        "EN" => 3,
        "ES" => 4,
        "AN" => 5,
        "NSM" => 6,
        "BN" => 7,
        "ON" => 8,
        other => panic!("unexpected bidi class {other:?}"),
    }
}

/// A plain `code point -> [code points]` mapping table (ILT03, ILT11, FLT12–23).
fn emit_mapping(out: &mut String, name: &str, text: &str) {
    let mut rows: Vec<(u32, Vec<u32>)> = data_lines(text)
        .map(|l| {
            let mut it = l.splitn(2, ',');
            let cp = parse_cp(it.next().unwrap());
            let to = parse_cp_list(it.next().unwrap_or(""));
            (cp, to)
        })
        .collect();
    rows.sort_unstable_by_key(|&(cp, _)| cp);
    write!(out, "pub static {name}: &[(u32, &[u32])] = &[").unwrap();
    for (cp, to) in rows {
        write!(out, "({cp},&[").unwrap();
        for cp in to {
            write!(out, "{cp},").unwrap();
        }
        out.push_str("]),");
    }
    out.push_str("];\n");
}

/// ILT02 drives two tables: the canonical decomposition map (like ILT03) and the
/// canonical-composition reverse map used by `c2_compose` — every 2-code-point
/// mapping that is *not* a full composition exclusion, keyed by its ordered pair.
fn emit_canonical(out: &mut String, text: &str) {
    let mut decomp: Vec<(u32, Vec<u32>)> = Vec::new();
    let mut compose: Vec<(u32, u32, u32)> = Vec::new();
    for l in data_lines(text) {
        let mut it = l.split(',');
        let cp = parse_cp(it.next().unwrap());
        let mapping = parse_cp_list(it.next().unwrap());
        let fce = it.next().unwrap().trim() == "1";
        if mapping.len() == 2 && !fce {
            compose.push((mapping[0], mapping[1], cp));
        }
        decomp.push((cp, mapping));
    }
    decomp.sort_unstable_by_key(|&(cp, _)| cp);
    compose.sort_unstable_by(|a, b| (a.0, a.1).cmp(&(b.0, b.1)));

    write!(out, "pub static ILT02_CANONICAL: &[(u32, &[u32])] = &[").unwrap();
    for (cp, to) in decomp {
        write!(out, "({cp},&[").unwrap();
        for cp in to {
            write!(out, "{cp},").unwrap();
        }
        out.push_str("]),");
    }
    out.push_str("];\n");

    write!(out, "pub static ILT02_COMPOSE: &[(u32, u32, u32)] = &[").unwrap();
    for (a, b, c) in compose {
        write!(out, "({a},{b},{c}),").unwrap();
    }
    out.push_str("];\n");
}
